name: jappcare
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  hugeicons: ^0.0.7
  huge_icons_flutter: ^0.0.2
  get: ^4.7.2
  get_storage: 2.1.1
  dartz: 0.10.1
  intl: ^0.20.2
  http: ^1.2.2
  shimmer: ^3.0.0
  cached_network_image: ^3.4.0
  google_fonts: ^6.2.1

  flutter_svg: ^2.0.10+1
  animated_theme_switcher: ^2.0.10
  flutter_spinkit: ^5.2.1
  responsive_framework: ^1.5.1
  talker_dio_logger: ^4.4.1
  flutter: 
    sdk: flutter
  dio_cache_interceptor_hive_store: ^4.0.0
  fluentui_system_icons: ^1.1.259

  loading_animation_widget: ^1.3.0
  dio_cache_interceptor_file_store: ^1.2.3
  path_provider: ^2.1.4
  talker: ^4.4.1
  dio_cache_interceptor: ^3.5.0
  dio: ^5.7.0
  country_code_picker: ^3.0.0
  pinput: ^5.0.0
  fl_chart: ^0.70.2
  image_picker: ^1.1.2
  carousel_slider: ^5.0.0
  google_maps_flutter: ^2.10.0
  permission_handler: ^12.0.0+1
  geolocator: ^13.0.2
  shared_preferences: ^2.3.5
  web_socket_channel: ^3.0.2
  image: any
  flutter_map: ^8.1.1
  google_sign_in: ^6.3.0

dev_dependencies: 
  icons_launcher: ^3.0.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
    assets:
      - assets/
      - assets/images/
      - assets/icons/
    fonts:
      - family: PlusJakarta
        fonts:
          - asset: assets/fonts/PlusJakarta.ttf
          - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
    uses-material-design: true

icons_launcher:
  image_path: "assets/icons/icon_launcher.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true


